-- Create scaglioni table
create table if not exists public.scaglioni (
  id bigint generated by default as identity primary key,
  soglia numeric not null,
  soglia_fine numeric, -- null implies infinity
  percentuale numeric not null,
  descrizione text,
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.scaglioni enable row level security;

-- Create policies
create policy "Enable read access for all users" on public.scaglioni
  for select using (true);

create policy "Enable insert access for all users" on public.scaglioni
  for insert with check (true);

create policy "Enable update access for all users" on public.scaglioni
  for update using (true);

create policy "Enable delete access for all users" on public.scaglioni
  for delete using (true);

-- Insert default data
insert into public.scaglioni (soglia, soglia_fine, percentuale, descrizione) values
  (1000, 15000, 10, '1.000 - 15.000€'),
  (15000, 50000, 5, '15.000 - 50.000€'),
  (50000, 100000, 2, '50.000 - 100.000€'),
  (100000, 300000, 1.5, '100.000 - 300.000€'),
  (300000, 1000000, 1, '300.000 - 1.000.000€'),
  (1000000, null, 0.5, 'Oltre 1.000.000€');
